name: Deploy NodeJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu
    steps:
      - name: Checkout Code
        uses: action/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.53.137.242
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/nodeJs-app-deploy-Githubactions
            git pull
            docker compose up -d --build
